
//----------------------------------------
// The code is automatically generated by the GenlibLcl tool.
// Copyright © ying32. All Rights Reserved.
// 
// Licensed under Apache License 2.0
//
//----------------------------------------


package vcl


import (
    . "github.com/ying32/govcl/vcl/api"
    . "github.com/ying32/govcl/vcl/types"
    "unsafe"
)

type TSelectDirectoryDialog struct {
    IComponent
    instance unsafe.Pointer
}

// NewSelectDirectoryDialog
//
// 创建一个新的对象。
// 
// Create a new object.
func NewSelectDirectoryDialog(owner IComponent) *TSelectDirectoryDialog {
    s := new(TSelectDirectoryDialog)
    s.instance = unsafe.Pointer(SelectDirectoryDialog_Create(CheckPtr(owner)))
    return s
}

// AsSelectDirectoryDialog
//
// 动态转换一个已存在的对象实例。
// 
// Dynamically convert an existing object instance.
func AsSelectDirectoryDialog(obj interface{}) *TSelectDirectoryDialog {
    instance := getInstance(obj)
    if instance == nullptr { return nil }
    return &TSelectDirectoryDialog{instance: instance}
}

// Free 
//
// 释放对象。
// 
// Free object.
func (s *TSelectDirectoryDialog) Free() {
    if s.instance != nullptr {
        SelectDirectoryDialog_Free(s._instance())
        s.instance  = nullptr
    }
}

func (s *TSelectDirectoryDialog) _instance() uintptr {
    return uintptr(s.instance)
}

// Instance 
//
// 返回对象实例指针。
// 
// Return object instance pointer.
func (s *TSelectDirectoryDialog) Instance() uintptr {
    return s._instance()
}

// UnsafeAddr 
//
// 获取一个不安全的地址。
// 
// Get an unsafe address.
func (s *TSelectDirectoryDialog) UnsafeAddr() unsafe.Pointer {
    return s.instance
}

// IsValid 
//
// 检测地址是否为空。
// 
// Check if the address is empty.
func (s *TSelectDirectoryDialog) IsValid() bool {
    return s.instance != nullptr
}

// Is 
// 
// 检测当前对象是否继承自目标对象。
// 
// Checks whether the current object is inherited from the target object.
func (s *TSelectDirectoryDialog) Is() TIs {
    return TIs(s._instance())
}

// As 
//
// 动态转换当前对象为目标对象。
// 
// Dynamically convert the current object to the target object.
//func (s *TSelectDirectoryDialog) As() TAs {
//    return TAs(s._instance())
//}

// TSelectDirectoryDialogClass
//
// 获取类信息指针。
// 
// Get class information pointer.
func TSelectDirectoryDialogClass() TClass {
    return SelectDirectoryDialog_StaticClassType()
}

// Execute
//
// 执行。
func (s *TSelectDirectoryDialog) Execute() bool {
    return SelectDirectoryDialog_Execute(s._instance())
}

// FindComponent
//
// 查找指定名称的组件。
//
// Find the component with the specified name.
func (s *TSelectDirectoryDialog) FindComponent(AName string) *TComponent {
    return AsComponent(SelectDirectoryDialog_FindComponent(s._instance(), AName))
}

// GetNamePath
//
// 获取类名路径。
//
// Get the class name path.
func (s *TSelectDirectoryDialog) GetNamePath() string {
    return SelectDirectoryDialog_GetNamePath(s._instance())
}

// HasParent
//
// 是否有父容器。
//
// Is there a parent container.
func (s *TSelectDirectoryDialog) HasParent() bool {
    return SelectDirectoryDialog_HasParent(s._instance())
}

// Assign
//
// 复制一个对象，如果对象实现了此方法的话。
//
// Copy an object, if the object implements this method.
func (s *TSelectDirectoryDialog) Assign(Source IObject) {
    SelectDirectoryDialog_Assign(s._instance(), CheckPtr(Source))
}

// ClassType
//
// 获取类的类型信息。
//
// Get class type information.
func (s *TSelectDirectoryDialog) ClassType() TClass {
    return SelectDirectoryDialog_ClassType(s._instance())
}

// ClassName
//
// 获取当前对象类名称。
//
// Get the current object class name.
func (s *TSelectDirectoryDialog) ClassName() string {
    return SelectDirectoryDialog_ClassName(s._instance())
}

// InstanceSize
//
// 获取当前对象实例大小。
//
// Get the current object instance size.
func (s *TSelectDirectoryDialog) InstanceSize() int32 {
    return SelectDirectoryDialog_InstanceSize(s._instance())
}

// InheritsFrom
//
// 判断当前类是否继承自指定类。
//
// Determine whether the current class inherits from the specified class.
func (s *TSelectDirectoryDialog) InheritsFrom(AClass TClass) bool {
    return SelectDirectoryDialog_InheritsFrom(s._instance(), AClass)
}

// Equals
//
// 与一个对象进行比较。
//
// Compare with an object.
func (s *TSelectDirectoryDialog) Equals(Obj IObject) bool {
    return SelectDirectoryDialog_Equals(s._instance(), CheckPtr(Obj))
}

// GetHashCode
//
// 获取类的哈希值。
//
// Get the hash value of the class.
func (s *TSelectDirectoryDialog) GetHashCode() int32 {
    return SelectDirectoryDialog_GetHashCode(s._instance())
}

// ToString
//
// 文本类信息。
//
// Text information.
func (s *TSelectDirectoryDialog) ToString() string {
    return SelectDirectoryDialog_ToString(s._instance())
}

func (s *TSelectDirectoryDialog) Files() *TStrings {
    return AsStrings(SelectDirectoryDialog_GetFiles(s._instance()))
}

func (s *TSelectDirectoryDialog) DefaultExt() string {
    return SelectDirectoryDialog_GetDefaultExt(s._instance())
}

func (s *TSelectDirectoryDialog) SetDefaultExt(value string) {
    SelectDirectoryDialog_SetDefaultExt(s._instance(), value)
}

func (s *TSelectDirectoryDialog) FileName() string {
    return SelectDirectoryDialog_GetFileName(s._instance())
}

func (s *TSelectDirectoryDialog) SetFileName(value string) {
    SelectDirectoryDialog_SetFileName(s._instance(), value)
}

func (s *TSelectDirectoryDialog) Filter() string {
    return SelectDirectoryDialog_GetFilter(s._instance())
}

func (s *TSelectDirectoryDialog) SetFilter(value string) {
    SelectDirectoryDialog_SetFilter(s._instance(), value)
}

func (s *TSelectDirectoryDialog) FilterIndex() int32 {
    return SelectDirectoryDialog_GetFilterIndex(s._instance())
}

func (s *TSelectDirectoryDialog) SetFilterIndex(value int32) {
    SelectDirectoryDialog_SetFilterIndex(s._instance(), value)
}

func (s *TSelectDirectoryDialog) InitialDir() string {
    return SelectDirectoryDialog_GetInitialDir(s._instance())
}

func (s *TSelectDirectoryDialog) SetInitialDir(value string) {
    SelectDirectoryDialog_SetInitialDir(s._instance(), value)
}

func (s *TSelectDirectoryDialog) Options() TOpenOptions {
    return SelectDirectoryDialog_GetOptions(s._instance())
}

func (s *TSelectDirectoryDialog) SetOptions(value TOpenOptions) {
    SelectDirectoryDialog_SetOptions(s._instance(), value)
}

func (s *TSelectDirectoryDialog) Title() string {
    return SelectDirectoryDialog_GetTitle(s._instance())
}

func (s *TSelectDirectoryDialog) SetTitle(value string) {
    SelectDirectoryDialog_SetTitle(s._instance(), value)
}

// Handle
//
// 获取控件句柄。
//
// Get Control handle.
func (s *TSelectDirectoryDialog) Handle() HWND {
    return SelectDirectoryDialog_GetHandle(s._instance())
}

func (s *TSelectDirectoryDialog) SetOnClose(fn TNotifyEvent) {
    SelectDirectoryDialog_SetOnClose(s._instance(), fn)
}

// SetOnShow
//
// 设置显示事件。
func (s *TSelectDirectoryDialog) SetOnShow(fn TNotifyEvent) {
    SelectDirectoryDialog_SetOnShow(s._instance(), fn)
}

// ComponentCount
//
// 获取组件总数。
//
// Get the total number of components.
func (s *TSelectDirectoryDialog) ComponentCount() int32 {
    return SelectDirectoryDialog_GetComponentCount(s._instance())
}

// ComponentIndex
//
// 获取组件索引。
//
// Get component index.
func (s *TSelectDirectoryDialog) ComponentIndex() int32 {
    return SelectDirectoryDialog_GetComponentIndex(s._instance())
}

// SetComponentIndex
//
// 设置组件索引。
//
// Set component index.
func (s *TSelectDirectoryDialog) SetComponentIndex(value int32) {
    SelectDirectoryDialog_SetComponentIndex(s._instance(), value)
}

// Owner
//
// 获取组件所有者。
//
// Get component owner.
func (s *TSelectDirectoryDialog) Owner() *TComponent {
    return AsComponent(SelectDirectoryDialog_GetOwner(s._instance()))
}

// Name
//
// 获取组件名称。
//
// Get the component name.
func (s *TSelectDirectoryDialog) Name() string {
    return SelectDirectoryDialog_GetName(s._instance())
}

// SetName
//
// 设置组件名称。
//
// Set the component name.
func (s *TSelectDirectoryDialog) SetName(value string) {
    SelectDirectoryDialog_SetName(s._instance(), value)
}

// Tag
//
// 获取对象标记。
//
// Get the control tag.
func (s *TSelectDirectoryDialog) Tag() int {
    return SelectDirectoryDialog_GetTag(s._instance())
}

// SetTag
//
// 设置对象标记。
//
// Set the control tag.
func (s *TSelectDirectoryDialog) SetTag(value int) {
    SelectDirectoryDialog_SetTag(s._instance(), value)
}

// Components
//
// 获取指定索引组件。
//
// Get the specified index component.
func (s *TSelectDirectoryDialog) Components(AIndex int32) *TComponent {
    return AsComponent(SelectDirectoryDialog_GetComponents(s._instance(), AIndex))
}

