// Automatically generated by the simple GoVCL IDE.
// 不要更改此文件名
// 在这里写你的事件。

package main

import (
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types"
)

//::private::
type TNewBaiduTranslateEngineFields struct {
}

func (f *TNewBaiduTranslateEngine) OnFormCreate(sender vcl.IObject) {

}

func (f *TNewBaiduTranslateEngine) OnBtnOKClick(sender vcl.IObject) {
	if showNotAllowEmpty(f.EdtName, "名称/别名") {
		return
	}
	if showNotAllowEmpty(f.EdtAppId, "AppId") {
		return
	}
	if showNotAllowEmpty(f.EditAppSecret, "AppSecret") {
		return
	}

	f.SetModalResult(types.MrOk)
}
